url: http://www.dronepiggy.com
baseurl:

# Site settings
title: FLYING PIGGY
email: fly@dronepiggy.com
description: "Aerial drone photography and videography production company based in Los Angeles, CA. Aerial cinematography, photography, videography, mapping, construction, real-estate, weddings and more! Competitive pricing and quotes available for our aerial drone video production and post-production services."


# SEO
facebook:
  publisher: http://facebook.com/dronepiggy
logo: /img/logo.png
google_site_verification: google8bc5aec39202e854

image:
  twitter: /img/logo.png

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 35C6F1
  secondary: FF99CC
  secondary-dark: 10174A

# Team names, titles and social links
people:
- name: Mikka Pineda
  pic: 1
  position: Co-Founder

- name: Zak Crawford
  pic: 2
  position: Co-Founder

- name: Baluntut Pillow
  pic: 3
  position: Moral Support

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  -
    url: http://facebook.com/dronepiggy
    title: facebook

# Postal address (add as many lines as necessary)
address:
  - line: Los Angeles, CA

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-seo-tag
